"""
Report generation system for WiFiSniper
"""

import os
import json
import csv
from datetime import datetime
from core.logger import Logger
from core.config import get_config
from utils.helpers import format_table

logger = Logger()

class ReportGenerator:
    def __init__(self):
        self.logger = logger

    def generate_scan_report(self, scan_data, format_type='text'):
        """Generate a report from scan data"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"scan_report_{timestamp}"

        if format_type == 'json':
            return self._generate_json_report(scan_data, f"{filename}.json")
        elif format_type == 'csv':
            return self._generate_csv_report(scan_data, f"{filename}.csv")
        else:
            return self._generate_text_report(scan_data, f"{filename}.txt")

    def _generate_text_report(self, scan_data, filename):
        """Generate text format report"""
        try:
            with open(filename, 'w') as f:
                f.write("WiFiSniper Network Scan Report\n")
                f.write("="*50 + "\n")
                f.write(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Interface: {scan_data.get('interface', 'Unknown')}\n")
                f.write(f"Scan Duration: {scan_data.get('duration', 'Unknown')} seconds\n\n")

                # Networks section
                if 'networks' in scan_data and scan_data['networks']:
                    f.write(f"NETWORKS FOUND: {len(scan_data['networks'])}\n")
                    f.write("-" * 30 + "\n")

                    for i, network in enumerate(scan_data['networks'], 1):
                        f.write(f"\n{i}. Network: {network.get('essid', 'Unknown')}\n")
                        f.write(f"   BSSID: {network.get('bssid', 'Unknown')}\n")
                        f.write(f"   Channel: {network.get('channel', 'Unknown')}\n")
                        f.write(f"   Encryption: {network.get('privacy', 'Unknown')}\n")
                        f.write(f"   Signal: {network.get('power', 'Unknown')} dBm\n")
                        f.write(f"   Clients: {network.get('clients', 0)}\n")

                # Clients section
                if 'clients' in scan_data and scan_data['clients']:
                    f.write(f"\n\nCLIENTS FOUND: {len(scan_data['clients'])}\n")
                    f.write("-" * 30 + "\n")

                    for i, client in enumerate(scan_data['clients'], 1):
                        f.write(f"\n{i}. MAC: {client.get('mac', 'Unknown')}\n")
                        f.write(f"   Signal: {client.get('power', 'Unknown')} dBm\n")
                        f.write(f"   Packets: {client.get('packets', 0)}\n")
                        if client.get('probed_essids'):
                            f.write(f"   Probed Networks: {client['probed_essids']}\n")

                f.write(f"\n\nReport generated by WiFiSniper\n")

            self.logger.success(f"Text report saved to: {filename}")
            return filename

        except Exception as e:
            self.logger.error(f"Failed to generate text report: {e}")
            return None

    def _generate_json_report(self, scan_data, filename):
        """Generate JSON format report"""
        try:
            report_data = {
                'metadata': {
                    'tool': 'WiFiSniper',
                    'version': '1.0',
                    'timestamp': datetime.now().isoformat(),
                    'interface': scan_data.get('interface'),
                    'duration': scan_data.get('duration')
                },
                'data': scan_data
            }

            with open(filename, 'w') as f:
                json.dump(report_data, f, indent=2)

            self.logger.success(f"JSON report saved to: {filename}")
            return filename

        except Exception as e:
            self.logger.error(f"Failed to generate JSON report: {e}")
            return None

    def _generate_csv_report(self, scan_data, filename):
        """Generate CSV format report"""
        try:
            with open(filename, 'w', newline='') as f:
                writer = csv.writer(f)

                # Networks CSV
                if 'networks' in scan_data and scan_data['networks']:
                    writer.writerow(['Type', 'BSSID', 'ESSID', 'Channel', 'Encryption', 'Signal', 'Clients'])
                    for network in scan_data['networks']:
                        writer.writerow([
                            'Network',
                            network.get('bssid', ''),
                            network.get('essid', ''),
                            network.get('channel', ''),
                            network.get('privacy', ''),
                            network.get('power', ''),
                            network.get('clients', 0)
                        ])

                # Clients CSV
                if 'clients' in scan_data and scan_data['clients']:
                    if scan_data['networks']:  # Add blank line if networks were written
                        writer.writerow([])
                    writer.writerow(['Type', 'MAC', 'Signal', 'Packets', 'Probed Networks'])
                    for client in scan_data['clients']:
                        writer.writerow([
                            'Client',
                            client.get('mac', ''),
                            client.get('power', ''),
                            client.get('packets', 0),
                            client.get('probed_essids', '')
                        ])

            self.logger.success(f"CSV report saved to: {filename}")
            return filename

        except Exception as e:
            self.logger.error(f"Failed to generate CSV report: {e}")
            return None

    def generate_attack_report(self, attack_data, format_type='text'):
        """Generate a report from attack data"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"attack_report_{timestamp}"

        try:
            with open(f"{filename}.txt", 'w') as f:
                f.write("WiFiSniper Attack Report\n")
                f.write("="*50 + "\n")
                f.write(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Attack Type: {attack_data.get('type', 'Unknown')}\n")
                f.write(f"Target: {attack_data.get('target', 'Unknown')}\n")
                f.write(f"Duration: {attack_data.get('duration', 'Unknown')}\n")
                f.write(f"Success: {attack_data.get('success', False)}\n")

                if attack_data.get('parameters'):
                    f.write(f"\nParameters:\n")
                    for key, value in attack_data['parameters'].items():
                        f.write(f"  {key}: {value}\n")

                if attack_data.get('results'):
                    f.write(f"\nResults:\n{attack_data['results']}\n")

                f.write(f"\nReport generated by WiFiSniper\n")

            self.logger.success(f"Attack report saved to: {filename}.txt")
            return f"{filename}.txt"

        except Exception as e:
            self.logger.error(f"Failed to generate attack report: {e}")
            return None

    def generate_vulnerability_report(self, vulnerabilities, format_type='text'):
        """Generate vulnerability report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"vulnerability_report_{timestamp}"

        try:
            with open(f"{filename}.txt", 'w') as f:
                f.write("WiFiSniper Vulnerability Assessment Report\n")
                f.write("="*60 + "\n")
                f.write(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Total Vulnerabilities Found: {len(vulnerabilities)}\n\n")

                severity_counts = {'high': 0, 'medium': 0, 'low': 0}
                for vuln in vulnerabilities:
                    severity_counts[vuln.get('severity', 'low')] += 1

                f.write("Summary by Severity:\n")
                f.write(f"  High: {severity_counts['high']}\n")
                f.write(f"  Medium: {severity_counts['medium']}\n")
                f.write(f"  Low: {severity_counts['low']}\n\n")

                for vuln in vulnerabilities:
                    f.write(f"[{vuln['severity'].upper()}] {vuln['network']}\n")
                    f.write(f"Type: {vuln['type']}\n")
                    f.write(f"Description: {vuln['description']}\n")
                    f.write(f"Recommendation: {vuln['recommendation']}\n")
                    f.write("-" * 50 + "\n")

                f.write(f"\nReport generated by WiFiSniper\n")

            self.logger.success(f"Vulnerability report saved to: {filename}.txt")
            return f"{filename}.txt"

        except Exception as e:
            self.logger.error(f"Failed to generate vulnerability report: {e}")
            return None

    def generate_session_summary(self, session_data):
        """Generate a session summary report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"session_summary_{timestamp}.txt"

        try:
            with open(filename, 'w') as f:
                f.write("WiFiSniper Session Summary\n")
                f.write("="*50 + "\n")
                f.write(f"Session Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Session Duration: {session_data.get('duration', 'Unknown')}\n\n")

                # Activity summary
                activities = session_data.get('activities', {})
                if activities:
                    f.write("Activity Summary:\n")
                    for activity_type, count in activities.items():
                        f.write(f"  {activity_type}: {count}\n")
                    f.write("\n")

                # Networks discovered
                networks = session_data.get('networks_discovered', 0)
                if networks > 0:
                    f.write(f"Networks Discovered: {networks}\n")

                # Attacks performed
                attacks = session_data.get('attacks_performed', 0)
                if attacks > 0:
                    f.write(f"Attacks Performed: {attacks}\n")

                # Vulnerabilities found
                vulns = session_data.get('vulnerabilities_found', 0)
                if vulns > 0:
                    f.write(f"Vulnerabilities Found: {vulns}\n")

                f.write(f"\nSession completed successfully\n")

            self.logger.success(f"Session summary saved to: {filename}")
            return filename

        except Exception as e:
            self.logger.error(f"Failed to generate session summary: {e}")
            return None

# Global report generator instance
report_generator = ReportGenerator()

def generate_scan_report(scan_data, format_type='text'):
    """Convenience function for scan reports"""
    return report_generator.generate_scan_report(scan_data, format_type)

def generate_attack_report(attack_data):
    """Convenience function for attack reports"""
    return report_generator.generate_attack_report(attack_data)

def generate_vulnerability_report(vulnerabilities):
    """Convenience function for vulnerability reports"""
    return report_generator.generate_vulnerability_report(vulnerabilities)